language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.6.9
  - DJANGO=1.7.2
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7.2
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
  - pip install -r test_requirements.pip
script:
  - coverage run --source=django_cron setup.py test
after_success:
  - coveralls
before_script:
  - mysql -e 'create database djangocron;'
