language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.7.7
  - DJANGO=1.8
addons:
  - postgresql: "9.3"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
  - pip install -r test_requirements.pip
script:
  - coverage run --source=django_cron setup.py test
after_success:
  - coveralls
before_script:
  - mysql -e 'create database travis_test;'
  - psql -c 'create database travis_test;' -U postgres
